from app.param_enums import FILE, ParamType

params_dict = {
    # -----------------------------------------------------------
                # command params
    "verbose": {
        "name": "verbose",
        "label": "Enable verbose mode",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
        "description": "Verbose option for debugging",
    },
    "debug": {
        "name": "debug",
        "label": "Enable debug mode",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "solver": {
        "name": "solver",
        "param_type": ParamType.SELECT,
        "label": "Select solver",
        "file": FILE.COMMAND,
        "optional": True,
        "values": ["knitro", "gurobi"],
    },
    "gams": {
        "name": "gams",
        "label": "Use gams",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "maxiter": {
        "name": "maxiter",
        "label": "Max iterations",
        "param_type": ParamType.BOOLEAN_WITH_INPUT,
        "file": FILE.COMMAND,
        "optional": False,
    },
    "maxtime": {
        "name": "maxtime",
        "label": "Set maxtime",
        "param_type": ParamType.SPIN_BOX,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "algorithm": {
        "name": "algorithm",
        "label": "Algorithm",
        "param_type": ParamType.SELECT,
        "file": FILE.COMMAND,
        "values": ["multistart", "mbh", "global_opt", "genetic", "population"],
        "description": "Selected algorithm for the simulation",
        "optional": True,
    },
    "no_starting_point": {
        "name": "no_starting_point",
        "label": "No starting point",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "no_simplified_model": {
        "name": "no_simplified_model",
        "label": "No simplified model",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "visualise": {
        "name": "visualise",
        "label": "Visualise",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "opex": {
        "name": "opex",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "capex": {
        "name": "capex",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "save_log_sol": {
        "name": "save_log_sol",
        "label": "Save sol log",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
        "description": "",
    },

    # -----------------------------------------------------------
    #                   config params
    "num_membranes": {
        "name": "num_membranes",
        "label": "Membranes floors",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "description": "number of membranes",
        "default": 1,
        "min_value": 0,
        "max_value": 3,  # the inital program assert <= 3
    },
    "ub_area": {
        "name": "ub_area",
        "label": "Upper bound area",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 6,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "lb_area": {
        "name": "lb_area",
        "label": "Lower bound area",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 0.2,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
    },
    "ub_acell": {
        "name": "ub_acell",
        "label": "Lower bound cell",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 0.2,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
    },
    "fixing_var": {
        "name": "fixing_var",
        "label": "Enable fixing var",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "uniform_pup": {
        "name": "uniform_pup",
        "label": "Uniform pup",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "vp": {
        "name": "vp",
        "label": "Vaccum pump",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "variable_perm": {
        "name": "variable_perm",
        "label": "Variable perm",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "max_no_improve": {
        "name": "max_no_improve",
        "label": "Max no improve",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 6,
        "min_value": 1,
        "max_value": 10000,
        "step": 1,
        "hidden": True
    },
    "max_trials": {
        "name": "max_trials",
        "label": "Max trials",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 11,
        "min_value": 1,
        "max_value": 10000,
        "step": 1,
        "hidden": True
    },
    "pressure_ratio": {
        "name": "pressure_ratio",
        "label": "Pressure ratio",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        # "default": 10.0,
        "min_value": 0,
        "max_value": 10,
        "step": 0.01,
    },
    "pop_size": {
        "name": "pop_size",
        "label": "Population size",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        # "default": 31,
        "min_value": 0,
        "max_value": 100,
        "step": 5,
        "hidden": True
    },
    "generations": {
        "name": "generations",
        "label": "Generations",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        # "default": 6,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "hidden": True,
    },
    "prototype_data": {
        "name": "prototype_data",
        "label": "Prototype data file",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": True,
    },
    "n1_element": {
        "name": "n1_element",
        "label": "N1 element",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "default": 6,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "optional": False,
        "hidden": True,
    },
    "iteration": {
        "name": "iteration",
        "label": "Iterations",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 300,
        "min_value": 1,
        "max_value": 10000,
        "step": 10,
        "hidden": False
    },
    "seed1": {
        "name": "seed1",
        "label": "Seed 1",
        "param_type": ParamType.SELECT,
        "file": FILE.CONFIG,
        "values": ["1", "2"],
        "optional": False,
        "hidden": False
    },
    "seed2": {
        "name": "seed2",
        "label": "Seed 2",
        "param_type": ParamType.SELECT,
        "file": FILE.CONFIG,
        "values": ["1", "2"],
        "optional": False,
        "hidden": True
    },
    # NOTE: seed à mettre éventuellement

    # -----------------------------------------------------------
    #               data.dat
    "param xin": {
        "name": "param xin",
        "label": "XIN",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param molarmass": {
        "name": "param molarmass",
        "label": "Molarmass",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param pressure_in": {
        "name": "param pressure_in",
        "label": "Pressure in",
        "param_type": ParamType.INPUT_WITH_UNITY,
        "values": ["Bar", "Pa", "kPa"],
        "file": FILE.DATA,
        "optional": False,
        "default": 2,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "set components": {
        "name": "set components",
        "label": "Set components",
        "param_type": ParamType.COMPONENT_SELECTOR,
        "file": FILE.DATA,
        "values": ["H20", "O2", "H2", "CO2", "N2"],
        "optional": False,
    },
    "param lb_perc_prod": {
        "name": "param lb_perc_prod",
        "label": "Lower bound perc prod",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param ub_perc_waste": {
        "name": "param ub_perc_waste",
        "label": "Upper bound perc waste",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param lb_perc_waste": {
        "name": "param lb_perc_waste",
        "label": "Lower bound perc waste",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param FEED": {
        "name": "param FEED",
        "label": "FEED",
        "param_type": ParamType.INPUT_WITH_UNITY,
        "values": ["mol/s"],
        "default": 0.02,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
        "file": FILE.DATA,
        "optional": False,
    },
    "param normalized_product_qt": {
        "name": "param normalized_product_qt",
        "label": "Normalized product qt",
        "param_type": ParamType.INPUT,
        "default": 0.95,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
        "file": FILE.DATA,
        "optional": False,
    },
    "param final_product": {
        "name": "param final_product",
        "label": "Final product",
        "param_type": ParamType.SELECT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param ub_press_down": {
        "name": "pram ub_press_down",
        "label": "Upper bound pressure down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "default": 1,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
        "optional": False,
    },
    "param lb_press_down": {
        "name": "param lb_press_down",
        "label": "Lower bound pressure down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param lb_press_down": {
        "name": "param lb_press_down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param lb_press_up": {
        "name": "param lb_press_up",
        "label": "Lower bound pressure up",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "param ub_press_up": {
        "name": "param ub_press_up",
        "label": "Upper bound press up",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 2,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "param pressure_prod": {
        "name": "param pressure_prod",
        "label": "Pressure prod",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 10,
        "min_value": 0,
        "max_value": 100,
        "step": 10,
    },
    "param lb_press_down": {
        "name": "param lb_press_down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_feed": {
        "name": "param ub_feed",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_feed_tot": {
        "name": "param ub_feed_tot",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_out_prod": {
        "name": "param ub_out_prod",
        "label": "Upper bound out prod",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_out_waste": {
        "name": "param ub_out_waste",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_feed": {
        "name": "param ub_feed",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param tol_zero": {
        "name": "tol_zero",
        "label": "Tol zero",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param n": {
        "name": "n",
        "label": "N",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "states": {
        "name": "states",
        "label": "States",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },

    # -----------------------------------------------------------
    #      perm file
    "set mem_types_set": {
        "name": "set mem_types_set",
        "label": "Mem types set",
        "param_type": ParamType.COMPONENT,
        "file": FILE.PERM,
        "values": ["M1", "M2", "M3"],
        "optional": False,
    },
    "param nb_gas": {
        "name": "param nb_gas",
        "label": "Nb gas",
        "param_type": ParamType.INPUT,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 2,
        "step": 1,
    },
    "param Permeability": {
        "name": "param Permeability",
        "label": "Permeability",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.PERM,
        "optional": False,
    },
    "param thickness": {
        "name": "param thickness",
        "label": "Thickness",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.PERM,
        "optional": False,
    },
    "param mem_type": {
        "name": "param mem_type",
        "label": "Mem type",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.PERM,
        "optional": False,
    },
    "param mem_product": {
        "name": "param mem_product",
        "label": "Mem product",
        # FIXME: fixed with select
        "param_type": ParamType.FIXED_WITH_SELECT,
        "file": FILE.PERM,
        "optional": False,
        "values": ["RET", "PERM"]
    },
    "alpha": {
        "name": "alpha",
        "label": "Alpha",
        "param_type": ParamType.INPUT,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 2,
        "step": 1,
    },
    "perm_ref": {
        "name": "perm_ref",
        "label": "Perm ref",
        "param_type": ParamType.INPUT,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 2,
        "step": 1,
    },

    # -----------------------------------------------------------
    #               eco file
    "param R": {
        "name": "param R",
        "label": "R",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 8.3144659848,
    },
    "param phi": {
        "name": "param phi",
        "label": "Phi",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.95,
    },
    "param T": {
        "name": "param T",
        "label": "Temperature",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 298.15,
    },
    "param gamma": {
        "name": "param gamma",
        "label": "Gamma",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 1.36,
    },
    "param C_cp": {
        "name": "param C_cp",
        "label": "C_cp",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 23000,
    },
    "param C_exp": {
        "name": "param C_exp",
        "label": "C_exp",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 420,
    },
    "param C_vp": {
        "name": "param C_vp",
        "label": "C_vp",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 1000,
    },
    "param eta_cp": {
        "name": "param eta_cp",
        "label": "Eta_cp",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.85,
    },
    "param K_mr": {
        "name": "param K_mr",
        "label": "K_mr",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 25,
    },
    "param K_gp": {
        "name": "param K_gp",
        "label": "K_gp",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0,
    },
    "param K_m": {
        "name": "param K_m",
        "label": "K_m",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 50,
    },
    "param K_mf": {
        "name": "param K_mf",
        "label": "K_mf",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 286000,
    },
    "param K_el": {
        "name": "param K_el",
        "label": "K_el",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.08,
    },
    "param K_er": {
        "name": "param K_er",
        "label": "K_er",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.9,
    },
    "param t_op": {
        "name": "param t_op",
        "label": "t_op",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 8322,
    },
    "param MFc": {
        "name": "param MFc",
        "label": "MFc",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 5.11,
    },
    "param nu": {
        "name": "param nu",
        "label": "Nu",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.25,
    },
    "param UF_2000": {
        "name": "param UF_2000",
        "label": "UF_2000",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 1.42,
    },
    "param UF_1968": {
        "name": "param UF_1968",
        "label": "UF_1968",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 4.99,
    },
    "param MPFc": {
        "name": "param MPFc",
        "label": "MPFc",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 2.72,
    },
    "param i": {
        "name": "param i",
        "label": "I",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.08,
    },
    "param z": {
        "name": "param z",
        "label": "Z",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 15,
    },
    "param eta_vp_1": {
        "name": "param eta_vp_1",
        "label": "Eta_vp_1",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.1058,
    },
    "param eta_vp_0": {
        "name": "param eta_vp_0",
        "label": "Eta_vp_0",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        # "default": 0.8746,
    },

#TODO: add fixing variables
# TODO: add a label for the question label in the param
}

