from app.param_enums import FILE, ParamType

params_dict = {
    # -----------------------------------------------------------
    # command params
    "verbose": {
        "name": "verbose",
        "label": "Enable verbose mode",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
        "description": "Verbose option for debugging",
    },
    "debug": {
        "name": "debug",
        "label": "Enable debug mode",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "solver": {
        "name": "solver",
        "param_type": ParamType.SELECT,
        "label": "Select solver",
        "file": FILE.COMMAND,
        "optional": True,
        "values": ["knitro", "ipopt"],
    },
    "gams": {
        "name": "gams",
        "label": "Use gams",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "maxiter": {
        "name": "maxiter",
        "label": "Max iterations",
        "param_type": ParamType.BOOLEAN_WITH_INPUT,
        "file": FILE.COMMAND,
        "optional": False,
    },
    "maxtime": {
        "name": "maxtime",
        "label": "Set maxtime",
        "param_type": ParamType.SPIN_BOX,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "algorithm": {
        "name": "algorithm",
        "label": "Algorithm",
        "param_type": ParamType.SELECT,
        "file": FILE.COMMAND,
        "values": ["multistart", "mbh", "global_opt", "genetic", "population"],
        "description": "Selected algorithm for the simulation",
        "optional": True,
    },
    "no_starting_point": {
        "name": "no_starting_point",
        "label": "No starting point",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "no_simplified_model": {
        "name": "no_simplified_model",
        "label": "No simplified model",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "visualise": {
        "name": "visualise",
        "label": "Visualise",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "opex": {
        "name": "opex",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "capex": {
        "name": "capex",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
    },
    "save_log_sol": {
        "name": "save_log_sol",
        "label": "Save sol log",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.COMMAND,
        "optional": True,
        "description": "",
    },
    # -----------------------------------------------------------
    #                   config params
    "num_membranes": {
        "name": "num_membranes",
        "label": "Membranes floors",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "expected_type": int,
        "description": "number of membranes",
        "default": 1,
        "min_value": 0,
        "max_value": 3,  # the inital program assert <= 3
    },
    "ub_area": {
        "name": "ub_area",
        "label": "Upper bound area",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 6,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "lb_area": {
        "name": "lb_area",
        "label": "Lower bound area",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 0.2,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
    },
    "ub_acell": {
        "name": "ub_acell",
        "label": "Lower bound cell",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.CONFIG,
        "default": 0.2,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
    },
    "fixing_var": {
        "name": "fixing_var",
        "label": "Enable fixing var",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
        "description": "If enabled, fixes variables as specified in fname_mask",
    },
    "uniform_pup": {
        "name": "uniform_pup",
        "label": "Uniform pup",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "vp": {
        "name": "vp",
        "label": "Vaccum pump",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "variable_perm": {
        "name": "variable_perm",
        "label": "Variable perm",
        "param_type": ParamType.BOOLEAN,
        "file": FILE.CONFIG,
        "optional": False,
    },
    "max_no_improve": {
        "name": "max_no_improve",
        "label": "Max no improve",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "expected_type": int,
        "default": 6,
        "min_value": 1,
        "max_value": 10000,
        "step": 1,
        "hidden": True,
        "description": "Maximum number of iterations allowed without improvement before stopping. Used in global_opt and mbh",
    },
    "max_trials": {
        "name": "max_trials",
        "label": "Max trials",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 11,
        "expected_type": int,
        "min_value": 1,
        "max_value": 10000,
        "step": 1,
        "hidden": True,
        "description": "Maximum number of trials for certain search or optimisation steps. Used in mbh and global_opt",
    },
    "pressure_ratio": {
        "name": "pressure_ratio",
        "label": "Pressure ratio",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 0.03,
        "min_value": 0,
        "max_value": 10,
        "step": 0.01,
        "description": "Threshold value for pressure-related variables in the model (used for contraints or tuning the optimisation)",
    },
    "pop_size": {
        "name": "pop_size",
        "label": "Population size",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 30,
        "min_value": 0,
        "max_value": 100,
        "step": 5,
        "hidden": True,
        "description": "Population size for evolutionary algorithms. Used in genetic algorithm",
        "expected_type": int,
    },
    "generations": {
        "name": "generations",
        "label": "Generations",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "optional": False,
        "default": 6,
        "expected_type": int,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "hidden": True,
        "description": "Number of generations for evolutionary algorithms. Used in genetic algorithm",
    },
    "prototype_data": {
        "name": "prototype_data",
        "label": "Prototype data file",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": True,
        "description": "Path to a YAML file containing prototype individuals for population initialization. Used in the population algorithm",
    },
    "n1_element": {
        "name": "n1_element",
        "label": "N1 element",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "expected_type": int,
        "default": 6,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "optional": False,
        "hidden": True,
        # "description": ""
    },
    "iteration": {
        "name": "iteration",
        "label": "Iterations",
        "param_type": ParamType.INPUT,
        "file": FILE.CONFIG,
        "expected_type": int,
        "optional": False,
        "default": 300,
        "min_value": 1,
        "max_value": 10000,
        "step": 10,
        "hidden": False,
        "description": "Number of iterations to run in the multistart or global optimisation algorithm",
    },
    "seed1": {
        "name": "seed1",
        "label": "Seed 1",
        "param_type": ParamType.SELECT,
        "file": FILE.CONFIG,
        "values": ["1", "2"],
        "expected_type": int,
        "optional": False,
        "hidden": False,
        "description": "Random seeds for reproductibility in stochastic parts of the algorithm, used in multistart, mbh and global optimisation",
    },
    "seed2": {
        "name": "seed2",
        "label": "Seed 2",
        "param_type": ParamType.SELECT,
        "file": FILE.CONFIG,
        "expected_type": int,
        "values": ["1", "2"],
        "optional": False,
        "hidden": True,
        "description": "Random seeds for reproductibility in stochastic parts of the algorithm, used in mbh and global optimisation",
    },
    "fname_mask": {
        "name": "fname_mask",
        "label": "Fixing file",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": True,
        "description": "Path to mask file for fixing variables (used if fixing_var is True)",
    },
    "fname": {
        "name": "fname",
        "label": "Data file",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": False,
        "description": "Path to data file used by the model",
    },
    "fname_perm": {
        "name": "fname_perm",
        "label": "Permeability File",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": False,
        "description": "Path to permeability file used by the model",
    },
    "fname_eco": {
        "name": "fname_eco",
        "label": "Economics file",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "optional": False,
        "hidden": False,
        "description": "Path to economics file used by the model",
    },
    "log_dir": {
        "name": "log_dir",
        "label": "Log Directory",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "description": "Directory to store log files",
        "default": "../mind/log/",
        "select_dir": True,
    },
    "data_dir": {
        "name": "data_dir",
        "label": "Data Directory",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "description": "Directory to store data files, used if the option --instance is used",
        "default": "../mind/data/",
        "select_dir": True,
    },
    "file_dir": {
        "name": "file_dir",
        "label": "File directory",
        "param_type": ParamType.FILECHOOSER,
        "file": FILE.CONFIG,
        "description": "",
        "default": "./test",
        "select_dir": True,
    },
    # -----------------------------------------------------------
    #               data.dat
    "param XIN": {
        "name": "param XIN",
        "label": "XIN",
        "param_type": ParamType.FIXED_COMPONENT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.5,
    },
    "param molarmass": {
        "name": "param molarmass",
        "label": "Molarmass",
        "param_type": ParamType.FIXED_COMPONENT,
        "file": FILE.DATA,
        "optional": False,
        "default": 2
    },
    "param pressure_in": {
        "name": "param pressure_in",
        "label": "Pressure in",
        "param_type": ParamType.INPUT_WITH_UNITY,
        "values": ["Bar", "Pa", "kPa"],
        "file": FILE.DATA,
        "optional": False,
        "default": 2,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "set components": {
        "name": "set components",
        "label": "Set components",
        "param_type": ParamType.COMPONENT_SELECTOR,
        "file": FILE.DATA,
        "values": ["O2", "H2", "CO2", "N2"],
        "optional": False,
    },
    "param lb_perc_prod": {
        "name": "param lb_perc_prod",
        "label": "Lower bound perc prod",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param ub_perc_waste": {
        "name": "param ub_perc_waste",
        "label": "Upper bound perc waste",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param lb_perc_waste": {
        "name": "param lb_perc_waste",
        "label": "Lower bound perc waste",
        "param_type": ParamType.FIXED_WITH_INPUT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param FEED": {
        "name": "param FEED",
        "label": "FEED",
        "param_type": ParamType.INPUT_WITH_UNITY,
        "values": ["mol/s"],
        "default": 0.02,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
        "file": FILE.DATA,
        "optional": False,
    },
    "param normalized_product_qt": {
        "name": "param normalized_product_qt",
        "label": "Normalized product qt",
        "param_type": ParamType.INPUT,
        "default": 0.95,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
        "file": FILE.DATA,
        "optional": False,
    },
    "param final_product": {
        "name": "param final_product",
        "label": "Final product",
        "param_type": ParamType.SELECT,
        "file": FILE.DATA,
        "optional": False,
    },
    "param ub_press_down": {
        "name": "param ub_press_down",
        "label": "Upper bound pressure down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "default": 1,
        "min_value": 0,
        "max_value": 10,
        "step": 0.1,
        "optional": False,
    },
    "param lb_press_down": {
        "name": "param lb_press_down",
        "label": "Lower bound pressure down",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1.0,
        "min_value": 1,
        "max_value": 10,
        "step": 0.1,
    },
    "param lb_press_up": {
        "name": "param lb_press_up",
        "label": "Lower bound pressure up",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "param ub_press_up": {
        "name": "param ub_press_up",
        "label": "Upper bound press up",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 2,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    "param pressure_prod": {
        "name": "param pressure_prod",
        "label": "Pressure prod",
        "param_type": ParamType.INPUT,
        "values": ["Bar", "Pa", "kPa"],
        "file": FILE.DATA,
        "optional": False,
        "default": 10,
        "min_value": 0,
        "max_value": 100,
        "step": 10,
    },
    "param ub_feed": {
        "name": "param ub_feed",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    # FIXME: for bound look in the program code  for defaults
    "param ub_feed_tot": {
        "name": "param ub_feed_tot",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_out_prod": {
        "name": "param ub_out_prod",
        "label": "Upper bound out prod",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_out_waste": {
        "name": "param ub_out_waste",
        "label": "Upper bound out waste",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param ub_feed": {
        "name": "param ub_feed",
        "label": "Upper bound feed",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param tol_zero": {
        "name": "tol_zero",
        "label": "Tol zero",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 0.01,
        "min_value": 0,
        "max_value": 1,
        "step": 0.05,
    },
    "param n": {
        "name": "n",
        "label": "N",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "states": {
        "name": "states",
        "label": "States",
        "param_type": ParamType.INPUT,
        "file": FILE.DATA,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    # -----------------------------------------------------------
    #      perm file
    "set mem_types_set": {
        "name": "set mem_types_set",
        "label": "Set membranes",
        "param_type": ParamType.COMPONENT,
        "file": FILE.PERM,
        "values": ["A", "B", "C"],
        "optional": False,
    },
    "param nb_gas": {
        "name": "param nb_gas",
        "label": "Nb gas",
        "param_type": ParamType.INPUT,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 5,
        "step": 1,
        "hidden": True,
    },
    "param Permeability": {
        "name": "param Permeability",
        "label": "Permeability",
        "param_type": ParamType.FIXED_PERM,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        # "hidden": True
    },
    "param thickness": {
        "name": "param thickness",
        "label": "Thickness",
        "param_type": ParamType.FIXED_MEMBRANE,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
    },
    "param mem_type": {
        "name": "param mem_type",
        "label": "Mem type",
        "param_type": ParamType.FIXED_MEM_TYPE,
        "file": FILE.PERM,
        "optional": False,
    },
    "param mem_product": {
        "name": "param mem_product",
        "label": "Mem product",
        # FIXME: fixed with select
        "param_type": ParamType.FIXED_MEMBRANE_SELECT,
        "file": FILE.PERM,
        "optional": False,
        "values": ["RET", "PERM"],
    },
    # TODO: add proper types for all variable perm params
    "alpha": {
        "name": "alpha",
        "label": "Alpha",
        "param_type": ParamType.INPUT,
        "file": FILE.PERM,
        "optional": False,
        "default": 1,
        "min_value": 0,
        "max_value": 2,
        "step": 1,
        "hidden": False,
    },
    "param Robeson_multi": {
        "name": "param Robeson_multi",
        "label": "Robeson_multi",
        "param_type": ParamType.FIXED_MEMBRANE,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "min_value": 0,
        "max_value": 2000000,
        "default": 1396000,
        "expected_type": int,
    },
    "param Robeson_power": {
        "name": "param Robeson_power",
        "label": "Robeson_power",
        "param_type": ParamType.FIXED_MEMBRANE,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "min_value": -10,
        "default": -5.666
    },
    "param ub_alpha": {
        "name": "param ub_alpha",
        "label": "Upper bound alpha",
        "param_type": ParamType.FIXED_MEMBRANE,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "default": 15,
    },
    "param lb_alpha": {
        "name": "param lb_alpha",
        "label": "Lower bound alpha",
        "param_type": ParamType.FIXED_MEMBRANE,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "default": 1.5,
    },
    "param lb_permeability": {
        "name": "param lb_permeability",
        "label": "Lower bound permeability",
        "param_type": ParamType.FIXED_MATRIX,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "default": 0.1,
        # "max_value": 100,
        # "min_value": 0,
        "step": 0.1,
    },
    "param ub_permeability": {
        "name": "param ub_permeability",
        "label": "Upper bound permeability",
        "param_type": ParamType.FIXED_MATRIX,
        "file": FILE.PERM,
        "optional": False,
        "hidden": True,
        "default": 10000,
        "max_value": 20000, 
        "step": 1000,
    },
    # -----------------------------------------------------------
    #               eco file
    "param R": {
        "name": "param R",
        "label": "Ideal Gas Constant",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 8.3144659848,
        "min_value": 0.0,
        "max_value": 100.0,
        "step": 0.0001,
    },
    "param phi": {
        "name": "param phi",
        "label": "Mechanical Efficiency",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.95,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.01,
    },
    "param T": {
        "name": "param T",
        "label": "Temperature",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 298.15,
        "min_value": 0.0,
        "max_value": 2000.0,
        "step": 0.01,
    },
    "param gamma": {
        "name": "param gamma",
        "label": "Gas Expansion Coefficient",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 1.36,
        "min_value": 0.0,
        "max_value": 2.0,
        "step": 0.01,
    },
    "param C_cp": {
        "name": "param C_cp",
        "label": "Compressor Base Cost",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 23000,
        "min_value": 0,
        "max_value": 1000000,
        "step": 100,
    },
    "param C_exp": {
        "name": "param C_exp",
        "label": "Expander Base Cost",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 420,
        "min_value": 0,
        "max_value": 1000000,
        "step": 10,
    },
    "param C_vp": {
        "name": "param C_vp",
        "label": "Vaccum Pump Cost Factor",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 1000,
        "min_value": 0,
        "max_value": 1000000,
        "step": 10,
    },
    "param eta_cp": {
        "name": "param eta_cp",
        "label": "Compressor Efficiency",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.85,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.01,
    },
    "param K_mr": {
        "name": "param K_mr",
        "label": "Membrane Replacement Cost",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 25,
        "min_value": 0,
        "max_value": 10000,
        "step": 1,
    },
    "param K_gp": {
        "name": "param K_gp",
        "label": "Upgraded Biogas Sales Price",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0,
        "min_value": 0,
        "max_value": 10000,
        "step": 1,
    },
    "param K_m": {
        "name": "param K_m",
        "label": "Membrane Module Unit Cost",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 50,
        "min_value": 0,
        "max_value": 10000,
        "step": 1,
    },
    "param K_mf": {
        "name": "param K_mf",
        "label": "Membrane Frame Base Cost",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 286000,
        "min_value": 0,
        "max_value": 1000000,
        "step": 100,
    },
    "param K_el": {
        "name": "param K_el",
        "label": "Electricity Cost Factor",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.08,
        "min_value": 0.0,
        "max_value": 10.0,
        "step": 0.01,
    },
    "param K_er": {
        "name": "param K_er",
        "label": "Exchange Rate",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.9,
        "min_value": 0.0,
        "max_value": 10.0,
        "step": 0.01,
    },
    "param t_op": {
        "name": "param t_op",
        "label": "Operation Time per Year",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 8322,
        "min_value": 0,
        "max_value": 8760,
        "step": 1,
    },
    "param MFc": {
        "name": "param MFc",
        "label": "Module Factor for Compressor",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 5.11,
        "min_value": 0.0,
        "max_value": 100.0,
        "step": 0.01,
    },
    "param nu": {
        "name": "param nu",
        "label": "Membrane Replacement Rate",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.25,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.01,
    },
    "param UF_2000": {
        "name": "param UF_2000",
        "label": "Update Factor 2000",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 1.42,
        "min_value": 0.0,
        "max_value": 10.0,
        "step": 0.01,
    },
    "param UF_1968": {
        "name": "param UF_1968",
        "label": "Update factor 2011",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 4.99,
        "min_value": 0.0,
        "max_value": 10.0,
        "step": 0.01,
    },
    "param MPFc": {
        "name": "param MPFc",
        "label": "Material & Pressure Factor for Compressor",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 2.72,
        "min_value": 0.0,
        "max_value": 100.0,
        "step": 0.01,
    },
    "param i": {
        "name": "param i",
        "label": "Interest Rate",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.08,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.01,
    },
    "param z": {
        "name": "param z",
        "label": "Project Lifetime",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 15,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "param eta_vp_1": {
        "name": "param eta_vp_1",
        "label": "Vaccum Pump Efficiency Slope",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.1058,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.0001,
    },
    "param eta_vp_0": {
        "name": "param eta_vp_0",
        "label": "Vaccum Pump Efficiency Offset",
        "param_type": ParamType.INPUT,
        "file": FILE.ECO,
        "optional": False,
        "default": 0.8746,
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.0001,
    },
    # -----------------------------------------------------------
    "fix area": {
        "name": "fix area",
        "label": "Fix membrane module area (fix area)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix splitFEED_frac": {
        "name": "fix splitFEED_frac ",
        "label": "Fix feed distribution to modules (fix splitFEED_frac)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix pressure_up": {
        "name": "fix pressure_up",
        "label": "Fix module pressures upstream (fix pressure_up)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix pressure_down": {
        "name": "fix pressure_down",
        "label": "Fix module pressures downstream (fix pressure_down)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix splitRET_frac": {
        "name": "fix splitRET_frac",
        "label": "Fix inter-stage split ret (fix splitRET_frac)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX_MATRIX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix splitPERM_frac": {
        "name": "fix splitPERM_frac",
        "label": "Fix inter-stage split perm (fix splitPERM_frac)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX_MATRIX,
        "file": FILE.MASK,
        "optional": False,
        "description": "Set the fraction of retentate/permeate from stage i entering stage j"
    },
    "fix splitOutPERM_frac": {
        "name": "fix splitOutPERM_frac",
        "label": "Fix output perm (fix splitOutPERM_frac)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    "fix splitOutRET_frac": {
        "name": "fix splitOutRET_frac",
        "label": "Fix output ret (fix splitOutRET_frac)",
        "param_type": ParamType.FIXED_COMPONENT_WITH_CHECKBOX,
        "file": FILE.MASK,
        "optional": False,
    },
    # ----------fixing var --------------------------------------
    # TODO: add descritions everywhere, especially the eco params
}
